config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORY = ['chinese', 'italian', 'japanese', 'french', 'belgian']

  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: CATEGORY }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true, in: (0..5) }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'reviews/new', status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
  <% @restaurants.each do |restaurant|  %>
    <div class="card">
      <img src="http://source.unsplash.com/featured/?food&<%= rand(50) %>)"/>
      <div class="card-info">
        <h2><%= link_to restaurant.name, restaurant_path(restaurant)%></h2>
        <p><strong><%= restaurant.category %></strong></p>
        <p><strong><%= restaurant.address %></strong></p>
      </div>
    </div>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <%= simple_form_for(@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :category, collection: Restaurant::CATEGORY %>
    <%= f.input :phone_number %>
    <%= f.button :submit, class: 'btn btn-primary w-100'%>
  <% end %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div>
    <div>
     <h1> <%= @restaurant.name %> </h1>
    </div>
    <div>
      <h2><%= @restaurant.category.capitalize() %></h2>
      <p><%= @restaurant.address %></p>
      <p><%= @restaurant.phone_number %></p>
      <% @restaurant.reviews.each do |review|  %>
        <%= review.content %>
        <%= review.rating.times do %>
          <i class="fas fa-star"></i>
        <% end %>
      <% end %>
      <div><%= link_to "Write a review", new_restaurant_review_path(@restaurant), class: "btn btn-primary" %></div>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
        <%= f.label :rating %>
  <div class="star-rating">
    <% 5.times do |i| %>
      <input type="radio" name="review[rating]" value="<%= i + 1 %>" <%= "checked" if i == 2 %> />
    <% end %>
  </div>
    <%= f.button :submit, class: 'btn btn-primary w-100'%>
  <% end %>
</div>